<a href="https://colab.research.google.com/github/JonathanJuradoS/UTP-IA-2025/blob/main/03_04_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html'> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# Missing Data (datos faltantes)

Vamos a mostrar algunos métodos convenientes para lidiar con los datos faltantes en Pandas:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df.fillna(value='PONER UN VALOR')

                A               B  C
0               1               5  1
1               2  PONER UN VALOR  2
2  PONER UN VALOR  PONER UN VALOR  3

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Excelente trabajo!